# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'XMLL2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~>3.8'
  pod "PYPhotoBrowser"
  # Pods for XMLL2

  target 'XMLL2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XMLL2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
